### ISSUE TITLE
Crash with the SOS shortcut

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar-client-android#349]
Confirmed with 5.11 from Google Play Store and master branch.
Steps to reproduce:

1. Install the client.
2. Start the application, allow location requests. (No configuration changes are needed).
3. Stop the application.
4. Close the application.
4. Make sure the phone's location services are turned **OFF**.

Then, using the application's shortcuts:

1. Send **SOS**. Result is "Send failed".
2. **Start** the service. Result is "Service started".
3. Send **SOS**. Result is "Send failed".
4. **Stop** the service. Result is "Service stopped".
5. Send **SOS**. The application crashes.

Crash report:

```
09-01 19:03:13.359 12877-12877/org.traccar.client E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.traccar.client, PID: 12877
    java.lang.IllegalStateException: LostApiClient is not connected.
        at com.mapzen.android.lost.internal.ApiImpl.throwIfNotConnected(ApiImpl.java:11)
        at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.getLastLocation(FusedLocationProviderApiImpl.java:134)
        at org.traccar.client.ShortcutActivity.onConnected(ShortcutActivity.java:115)
        at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.onServiceConnected(FusedLocationServiceConnectionManager.java:86)
        at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:94)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1634)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1663)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6589)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by oliv3** [comment]
Fix available in https://github.com/traccar/traccar-client-android/pull/348.

**Comment by oliv3** [comment]
Sure. Do you want particular branch names ?

**Comment by tananaev** [comment]
Not really. Just make it something relevant to the problem.

**Comment by oliv3** [comment]
Would bug_XXX be enough ?

**Comment by tananaev** [comment]
Sure.
